name: CI

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" 
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" 
          -d "text=ФИО за компьютера"
