name: Telegram Notification on Push

on:
  push:

jobs:
  telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const botToken = '${{ secrets.TELEGRAM_BOT_TOKEN }}';
            const chatId = '${{ secrets.TELEGRAM_CHAT_ID }}';
            const message = `ФИО за компьютером\n\nPush event detected on branch: ${context.payload.ref}\nCommit message: ${context.payload.commits[0].message}`;
            const apiUrl = `https://api.telegram.org/bot${botToken}/sendMessage`;
            const response = await fetch(apiUrl, {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                chat_id: chatId,
                text: message,
                parse_mode: "HTML" //добавил для HTML форматирования
              })
            });
            if (!response.ok) {
                console.error(`Failed to send Telegram message: ${response.status} ${response.statusText}`);
            } else {
              console.log('Telegram message sent successfully!');
            }
